package:
  name: gcc
  version: 4.8

source:
  fn: gcc-4.8.tar.bz2
  url: ftp://ftp.fu-berlin.de/unix/languages/gcc/snapshots/4.8-20140306/gcc-4.8-20140306.tar.bz2

requirements:
  build:
    # These are taken from the output of the configure scripts
    - gmp >=4.2
    - mpfr >=2.4.0
    - mpc >=0.8.0
    - isl
  run:
    - gmp >=4.2
    - mpfr >=2.4.0
    - mpc >=0.8.0
    - isl

about:
  home: http://gcc.gnu.org/
  summary: The GNU Compiler Collection
  license: GPL

